version = 0.1

[default.deploy.parameters]
stack_name = "portfolio-backend"
resolve_s3 = true
s3_prefix = "portfolio-backend"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "BlogsTable=\"BlogsTable\" CommentsTable=\"BlogCommentsTable\" SkillsTable=\"SkillsTable\" ProjectsTable=\"ProjectsTable\" ProfileTable=\"ProfileTable\" UsersTable=\"UsersTable\""
image_repositories = []

[default.global.parameters]
region = "ap-south-1"
